/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康检查（数据库） */
        get: operations["health_api_v1_system_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 版本与数据目录 */
        get: operations["info_api_v1_system_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 最近的任务 */
        get: operations["list_jobs_api_v1_system_jobs_get"];
        put?: never;
        /** 创建测试任务（幂等） */
        post: operations["create_job_api_v1_system_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 任务状态 */
        get: operations["get_job_api_v1_system_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 取消任务 */
        post: operations["cancel_job_api_v1_system_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/markets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 站点目录 */
        get: operations["markets_index_api_v1_markets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/markets/{market_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 单个站点 */
        get: operations["market_detail_api_v1_markets__market_code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前设置（不含密钥明文） */
        get: operations["get_settings_view_api_v1_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/llm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 保存大模型设置 */
        put: operations["put_llm_api_v1_settings_llm_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/fastmoss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 保存 FastMoss API Key（空字符串表示删除） */
        put: operations["put_fastmoss_api_v1_settings_fastmoss_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 外部服务连通检查 */
        post: operations["external_checks_api_v1_settings_checks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppInfo */
        AppInfo: {
            /** Version */
            version: string;
            /** Data Dir */
            data_dir: string;
        };
        /** CreateJobRequest */
        CreateJobRequest: {
            /**
             * Kind
             * @default system.noop
             * @constant
             */
            kind: "system.noop";
            /** Params */
            params?: {
                [key: string]: unknown;
            };
        };
        /** ExternalCheck */
        ExternalCheck: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "not_configured" | "error";
            /**
             * Detail
             * @default
             */
            detail: string;
            /** Model */
            model?: string | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Available Credits */
            available_credits?: number | null;
            /** Credit Cost */
            credit_cost?: number | null;
        };
        /** ExternalChecks */
        ExternalChecks: {
            llm: components["schemas"]["ExternalCheck"];
            fastmoss: components["schemas"]["ExternalCheck"];
        };
        /** FastMossSettingsUpdate */
        FastMossSettingsUpdate: {
            /** Api Key */
            api_key: string;
        };
        /** FastMossSettingsView */
        FastMossSettingsView: {
            /** Api Key Hint */
            api_key_hint: string | null;
            /** Configured */
            configured: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Version */
            version: string;
            /** Checks */
            checks: {
                [key: string]: string;
            };
        };
        /** JobView */
        JobView: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "waiting_input" | "cancel_requested" | "succeeded" | "partial" | "failed" | "cancelled";
            /** Stage */
            stage: string | null;
            /** Progress */
            progress: {
                [key: string]: unknown;
            } | null;
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /** Last Error */
            last_error: {
                [key: string]: unknown;
            } | null;
            /** Attempt */
            attempt: number;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /** LLMSettingsUpdate */
        LLMSettingsUpdate: {
            /**
             * Base Url
             * @default
             */
            base_url: string;
            /**
             * Model Matching
             * @default
             */
            model_matching: string;
            /**
             * Model Brief
             * @default
             */
            model_brief: string;
            /**
             * Structured Mode
             * @default json_schema
             * @enum {string}
             */
            structured_mode: "json_schema" | "function_calling" | "json_mode";
            /**
             * Timeout Seconds
             * @default 60
             */
            timeout_seconds: number;
            /**
             * Data Region
             * @default
             */
            data_region: string;
            /** Api Key */
            api_key?: string | null;
        };
        /** LLMSettingsView */
        LLMSettingsView: {
            /** Base Url */
            base_url: string;
            /** Model Matching */
            model_matching: string;
            /** Model Brief */
            model_brief: string;
            /**
             * Structured Mode
             * @enum {string}
             */
            structured_mode: "json_schema" | "function_calling" | "json_mode";
            /** Timeout Seconds */
            timeout_seconds: number;
            /** Data Region */
            data_region: string;
            /** Api Key Hint */
            api_key_hint: string | null;
            /** Configured */
            configured: boolean;
        };
        /** Market */
        Market: {
            /** Market Code */
            market_code: string;
            /** Name Zh */
            name_zh: string;
            /** Name En */
            name_en: string;
            /** Region Group */
            region_group: string;
            /** Settlement Currency */
            settlement_currency: string;
            /** Default Time Zone */
            default_time_zone: string;
            /** Content Languages */
            content_languages: string[];
            /** Fastmoss Region */
            fastmoss_region: string | null;
            /**
             * Data Status
             * @enum {string}
             */
            data_status: "queryable" | "queryable_currency_unknown" | "platform_unconfirmed" | "manual_import_only";
            /** Last Probe Total */
            last_probe_total: number | null;
            /** Probe Currency */
            probe_currency: string | null;
            /** Notes */
            notes: string;
        };
        /** SettingsView */
        SettingsView: {
            llm: components["schemas"]["LLMSettingsView"];
            fastmoss: components["schemas"]["FastMossSettingsView"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_system_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    info_api_v1_system_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppInfo"];
                };
            };
        };
    };
    list_jobs_api_v1_system_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"][];
                };
            };
        };
    };
    create_job_api_v1_system_jobs_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_system_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_v1_system_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    markets_index_api_v1_markets_get: {
        parameters: {
            query?: {
                region_group?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Market"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    market_detail_api_v1_markets__market_code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                market_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Market"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_view_api_v1_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsView"];
                };
            };
        };
    };
    put_llm_api_v1_settings_llm_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LLMSettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_fastmoss_api_v1_settings_fastmoss_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FastMossSettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    external_checks_api_v1_settings_checks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalChecks"];
                };
            };
        };
    };
}
