[package]
name = "tk-workspace"
version = "0.3.0"
description = "TK 多站点达人开发与内容运营工作台"
edition = "2021"
publish = false

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-single-instance = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
getrandom = "0.2"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
